# Generated by Django 5.0.6 on 2026-04-20 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Unique username for public profile URL', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Name displayed on profile', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short bio/description', max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('theme', models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme'), ('gradient_purple', 'Purple Gradient'), ('gradient_blue', 'Blue Gradient'), ('gradient_pink', 'Pink Gradient'), ('neon_cyan', 'Neon Cyan'), ('sunset', 'Sunset'), ('ocean', 'Ocean')], default='dark', max_length=50)),
                ('layout', models.CharField(choices=[('minimal', 'Minimal'), ('classic', 'Classic'), ('modern', 'Modern'), ('glassmorphism', 'Glassmorphism')], default='glassmorphism', max_length=50)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', help_text='Hex color code', max_length=7)),
                ('background_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('qr_code_enabled', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('twitter', 'Twitter/X'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('spotify', 'Spotify'), ('custom', 'Custom Link')], max_length=50)),
                ('title', models.CharField(help_text='Display title for the link', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('custom_color', models.CharField(blank=True, help_text='Custom color for this link', max_length=7)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='link_thumbnails/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which link appears (lower first)')),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='user_profile.userprofile')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
