# Generated by Django 5.0.6 on 2026-04-19 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('welMessage', models.CharField(blank=True, max_length=300, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('bussiness_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('theme', models.CharField(blank=True, choices=[('theme1', 'Theme 1'), ('theme2', 'Theme 2'), ('theme3', 'Theme 3'), ('theme4', 'Theme 4'), ('theme5', 'Theme 5'), ('theme6', 'Theme 6'), ('theme7', 'Theme 7'), ('theme8', 'Theme 8')], max_length=50, null=True)),
                ('layout', models.CharField(blank=True, choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3'), ('layout4', 'Layout 4'), ('layout5', 'Layout 5')], max_length=50, null=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background_images/')),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('font_style', models.CharField(blank=True, choices=[('font1', 'Font 1'), ('font2', 'Font 2'), ('font3', 'Font 3'), ('font4', 'Font 4'), ('font5', 'Font 5')], max_length=50, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
